# Use an official node.js image as the base image
FROM node:latest

# Create a working directory in the container
WORKDIR /app

# Copy all files and directories in the current directory to the working directory
COPY . .

